#!/bin/sh
set -e
case "$1" in
    remove|deconfigure)
        VENVDIR="/opt/kalinka/venv"
        if [ -x "$VENVDIR/bin/pip" ]; then
            "$VENVDIR/bin/pip" uninstall -y kalinka-plugin-spotify || true
        fi
        ;;
esac
exit 0
